name: Deploy to GitHub Pages
on:
  push:
    branches: [ main ]
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          npm install --force
          # Устанавливаем недостающий плагин вручную, чтобы он точно был
          npm install @vitejs/plugin-react-swc --save-dev

      - name: Build
        run: npx vite build --base=/pill-pal-pro-54/

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
